import type { Metadata } from "next";
import "./globals.css";
import ThemeToggle from "./components/ThemeToggle";
import { Source_Serif_4 } from "next/font/google"

const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-source-serif-4",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sourceSerif.variable} antialiased`}>
<body
  suppressHydrationWarning
  style={{
    background: "var(--color-background)",
    color: "var(--color-text-default)",
    fontFamily: "var(--font-source-serif-4)",
  }}
  className="min-h-screen antialiased"
>  
  <main className="mx-auto max-w-[680px] px-5 py-6 sm:px-8 sm:py-10">
  <div className="flex justify-end pb-4">
    <ThemeToggle />
  </div>
    {children}
  </main>
      </body>
    </html>
  );
}
